### ISSUE TITLE
It could be useful...

### ISSUE THREAD

**Issue by cvladan** [rostok/file2clip#2]
I have created a Scoop (package manager) manifest file in Gist. Anyone who wants to install this tool automatically can do so with:

```
scoop install https://gist.githubusercontent.com/cvladan/416c1945c9e446a6fc64ba766d6ee4ef/raw/file2clip.json
```

Should we put this in the README.md?

**Comment by cvladan** [comment]
And last but not least, **thank you** for this simple tool and for the time you put into it.

I still can't believe I haven't found another "more established" tool that does the same thing.

**Comment by rostok** [comment]
i have updated the readme. thx!
