### ISSUE TITLE
Unable to run .exe file using nodejs child_process

### ISSUE THREAD

**Issue by Souvikns** [rostok/file2clip#4]
I am trying to run the `file2clip.exe` using a nodejs script but for some reason I am unable to run the script successfully and the program does not stop.

```js
    const command = `${path.resolve('./file2clip.exe')} ${path.resolve('./test.txt')}}`
    await exec(command,{maxBuffer: 1024*1024}, (err, stdout, stderr) => {
        console.log(err, stdout, stderr)
    })
```
![image](https://github.com/user-attachments/assets/3bea7c63-7323-4529-a1da-35b6a832408b)

However the `file2clip.exe` works fine when I use it on the terminal on my own so it does not look like a permission issue. Also want to copy pdfs to the clipboard. Will it run into any problems with it.

**Comment by rostok** [comment]
what about simple `echo crow.txt | file2clip`

```
const path = require('node:path'); 
const { exec, spawn } = require('node:child_process');

async function go() {
const command = `echo ${path.resolve('./test.txt')} | ${path.resolve('./file2clip.exe')}`
await exec(command,{maxBuffer: 1024*1024}, (err, stdout, stderr) => {
    console.log(err, stdout, stderr)
})

}

go()
```

i think file2clip hangs on empty stdin, but once it is provided it should work just fine

**Comment by Souvikns** [comment]
Thanks now it works 🙏🏼
